version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT261125Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git261125.integrations:TestRestConnector
  packages:
  - name: SIQA_GIT261125Project
    version: "1.0"
